package com.nuvio.app.core.account

/*
 * Single source of truth for every persisted store that a full account sign-out must erase.
 *
 * Three hand-maintained lists used to own this knowledge independently and drifted apart:
 *  - `core.bootstrap.TvOsProviderInstaller`'s `TvOsAccountDataCleaner` (tvOS, NSUserDefaults),
 *  - composeApp's `PlatformLocalAccountDataCleaner.ios` (iOS, NSUserDefaults),
 *  - composeApp's `PlatformLocalAccountDataCleaner.android` (SharedPreferences file names),
 *  - `core.storage.AppleFilePayloadStores` (the file-backed PayloadFileStore subdirectories).
 *
 * Every entry below is TRANSCRIBED from the real key constants in each store's `actual` — never
 * inferred from a naming convention — and this list is a superset of the union of those four.
 *
 * ## Why this is a static list and not self-registration
 * A store that registered itself from its own `init {}` block would only register once something
 * touched the object: Kotlin `object` initializers are lazy, so a store nobody read during the
 * session would silently never register and would silently never be wiped. That is the exact
 * failure mode this registry exists to remove, so DO NOT add `init {}` hooks or a mutable
 * registration API here. Adding a store means adding a line to [AccountDataStores.all].
 *
 * ## Purity
 * This file is data only: no platform imports, no `expect`/`actual`, no NSUserDefaults or
 * SharedPreferences types. Each platform cleaner consumes the projections at the bottom.
 */

/**
 * How an Apple (iOS/tvOS) `NSUserDefaults` key is actually spelled at the call site. Getting this
 * wrong means the wipe silently misses the data, so each variant mirrors one concrete call shape
 * observed in the storage `actual`s.
 */
sealed interface AppleKeySpec {
    /** Raw unscoped key: `defaults.stringForKey("profile_payload")`. */
    data class Plain(val key: String) : AppleKeySpec

    /** `ProfileScopedKey.of(base)` → `"<base>_<activeProfileId>"`; wipe for every profile slot. */
    data class ProfileScoped(val base: String) : AppleKeySpec

    /** Key built inline as `"<prefix><profileId>"`; wipe for every profile slot. */
    data class ProfileIndexed(val prefix: String) : AppleKeySpec

    /**
     * Key embeds runtime data (a content-id hash, a scraper/manifest URL, a debrid provider id),
     * so it cannot be enumerated: wipe by scanning `defaults.dictionaryRepresentation()` and
     * removing every key that starts with [prefix]. [prefix] is the longest literal prefix that
     * is still safe to match on.
     */
    data class DynamicPrefix(val prefix: String) : AppleKeySpec

    /** A `core.storage.PayloadFileStore` subdirectory of Application Support. */
    data class FileStore(val subdirectory: String) : AppleKeySpec
}

/**
 * One persisted store.
 *
 * @param name the storage object that owns the data (for humans and for grep).
 * @param androidPreferences the `preferencesName` its `.android.kt` actual passes to
 *   `getSharedPreferences`, or null when the store has no Android backing at all.
 * @param appleKeys every key/prefix/subdirectory its Apple actual writes.
 */
data class AccountDataStore(
    val name: String,
    val androidPreferences: String?,
    val appleKeys: List<AppleKeySpec>,
)

object AccountDataStores {

    /**
     * Every store a sign-out must erase.
     *
     * Deliberately EXCLUDED, with reasons:
     *  - `SyncClientIdentityStorage` (`client_instance_id`, Android `nuvio_sync_client_identity`):
     *    a random per-INSTALL id (`nuvio-mobile-…`) generated by `core.sync.SyncClientIdentity` and
     *    sent as `p_origin_client_id` so the sync backend can suppress echoes of this device's own
     *    writes. It is device identity, not account data — it holds nothing about the user, and
     *    rotating it mid-flight only weakens echo suppression. It must SURVIVE sign-out.
     *  - `SentrySettingsStorage` (`sentry_enabled`, Android `nuvio_sentry_settings`): unscoped
     *    crash-reporting consent — a device/privacy choice, not account data.
     *  - `AppUpdaterPlatform` (Android `nuvio_updater`): update bookkeeping, no user data.
     *  - `ThemeSettingsStorage`'s UNSCOPED `selected_app_language` (and the system `AppleLanguages`
     *    key it drives): app language is stored without a profile suffix, i.e. deliberately
     *    device-wide. Only its LEGACY profile-scoped copy is wiped (see that entry).
     *  - `core.network.ServerConfigurationStorage` (Apple `server_custom_config` — one versioned
     *    JSON blob; Android prefs `server_configuration`): the
     *    self-hosted backend selection. Device/install configuration in the same class as
     *    `client_instance_id` — upstream never clears it on sign-out, and wiping it would silently
     *    bounce a self-hosted user back to api.nuvio.tv after every sign-out (and mid
     *    server-switch, whose prepare step runs this very wipe). It must SURVIVE sign-out.
     */
    val all: List<AccountDataStore> = listOf(

        // ── Identity / profiles ────────────────────────────────────────────────────────────────
        AccountDataStore(
            name = "AuthStorage",
            androidPreferences = "nuvio_auth",
            appleKeys = listOf(
                // NOTE: covered by the iOS cleaner's plainKeys but MISSING from the tvOS cleaner.
                AppleKeySpec.Plain("anonymous_user_id"),
            ),
        ),
        AccountDataStore(
            name = "ProfileStorage",
            androidPreferences = "nuvio_profile_cache",
            appleKeys = listOf(AppleKeySpec.Plain("profile_payload")),
        ),
        AccountDataStore(
            name = "AvatarStorage",
            androidPreferences = "nuvio_avatar_cache",
            appleKeys = listOf(AppleKeySpec.Plain("avatar_catalog_payload")),
        ),
        AccountDataStore(
            name = "ProfilePinCacheStorage",
            androidPreferences = "nuvio_profile_pin_cache",
            appleKeys = listOf(AppleKeySpec.ProfileIndexed("profile_pin_cache_")),
        ),

        // ── Add-ons & plugins ──────────────────────────────────────────────────────────────────
        AccountDataStore(
            name = "AddonStorage",
            androidPreferences = "nuvio_addons",
            appleKeys = listOf(
                AppleKeySpec.ProfileIndexed("installed_manifest_urls_"),
                // Written by saveAddonEnabledStates; covered by NO existing cleaner.
                AppleKeySpec.ProfileIndexed("installed_manifest_enabled_states_"),
            ),
        ),
        AccountDataStore(
            // tvOS: shared/tvosMain PluginStorage + appleMain PluginStateFiles.
            // iOS (iosFull): composeApp PluginPlatform.ios, still defaults-backed.
            name = "PluginStorage / PluginStateFiles",
            androidPreferences = "nuvio_plugins",
            appleKeys = listOf(
                AppleKeySpec.FileStore("PluginState"),
                // Legacy defaults payload; tvOS migrates it into PluginState on read, iOS still
                // writes it. Listed both statically and as a scan because iOS profile ids are not
                // bounded by MAX_PROFILES on old installs.
                AppleKeySpec.ProfileIndexed("plugins_state_"),
                AppleKeySpec.DynamicPrefix("plugins_state_"),
                // Per-scraper settings: the scraper id embeds the manifest URL, so keys look like
                // "settings_https://…". Kept at the exact prefix the cleaners already use —
                // broadening to "settings_" would sweep unrelated keys.
                AppleKeySpec.DynamicPrefix("settings_http"),
            ),
        ),

        // ── Library / watch state (all file-backed on Apple; defaults keys are pre-migration) ───
        AccountDataStore(
            name = "LibraryStorage",
            androidPreferences = "nuvio_library",
            appleKeys = listOf(
                AppleKeySpec.FileStore("Library"),
                AppleKeySpec.ProfileIndexed("library_payload_"),
            ),
        ),
        AccountDataStore(
            name = "WatchedStorage",
            androidPreferences = "nuvio_watched",
            appleKeys = listOf(
                AppleKeySpec.FileStore("Watched"),
                AppleKeySpec.ProfileIndexed("watched_payload_"),
            ),
        ),
        AccountDataStore(
            name = "WatchProgressStorage",
            androidPreferences = "nuvio_watch_progress",
            appleKeys = listOf(
                AppleKeySpec.FileStore("WatchProgress"),
                AppleKeySpec.ProfileIndexed("watch_progress_payload_"),
            ),
        ),
        AccountDataStore(
            name = "CollectionStorage",
            androidPreferences = "nuvio_collections",
            appleKeys = listOf(
                AppleKeySpec.FileStore("Collections"),
                AppleKeySpec.ProfileScoped("collections_payload"),
            ),
        ),
        AccountDataStore(
            name = "CollectionMobileSettingsStorage",
            androidPreferences = "nuvio_collection_mobile_settings",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("collection_mobile_settings_payload")),
        ),
        AccountDataStore(
            name = "LibraryDisplaySettingsStorage",
            androidPreferences = "nuvio_library_display_settings",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("library_display_settings_payload")),
        ),
        AccountDataStore(
            name = "ContinueWatchingPreferencesStorage",
            androidPreferences = "nuvio_continue_watching_preferences",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("continue_watching_preferences_payload")),
        ),
        AccountDataStore(
            name = "ContinueWatchingEnrichmentStorage",
            androidPreferences = "nuvio_cw_enrichment",
            appleKeys = listOf(
                AppleKeySpec.FileStore("ContinueWatchingEnrichment"),
                // Keys are "cw_enrichment_cache_<source>_<profile>" (and the legacy
                // "cw_enrichment_cache_<profile>"), built in ContinueWatchingEnrichmentCache.
                AppleKeySpec.DynamicPrefix("cw_enrichment_cache_"),
            ),
        ),
        AccountDataStore(
            name = "ResumePromptStorage",
            androidPreferences = "nuvio_resume_prompt",
            appleKeys = listOf(
                AppleKeySpec.ProfileScoped("nuvio_resume_prompt_was_in_player"),
                AppleKeySpec.ProfileScoped("nuvio_resume_prompt_last_player_video_id"),
            ),
        ),
        AccountDataStore(
            name = "DownloadsStorage",
            androidPreferences = "nuvio_downloads",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("downloads_payload")),
        ),
        AccountDataStore(
            // Mirror of the active download for the iOS Live Activity / Android notification.
            name = "DownloadsLiveStatusPlatform",
            androidPreferences = "nuvio_download_live_notifications",
            appleKeys = listOf(AppleKeySpec.Plain("nuvio.downloads.live_status.payload")),
        ),
        AccountDataStore(
            name = "SearchHistoryStorage",
            androidPreferences = "nuvio_search_history",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("search_history_payload")),
        ),

        // ── Catalog / details / appearance ──────────────────────────────────────────────────────
        AccountDataStore(
            name = "HomeCatalogSettingsStorage",
            androidPreferences = "nuvio_home_catalog_settings",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("catalog_settings_payload")),
        ),
        AccountDataStore(
            name = "MetaScreenSettingsStorage",
            androidPreferences = "nuvio_meta_screen_settings",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("meta_screen_settings_payload")),
        ),
        AccountDataStore(
            name = "SeasonViewModeStorage",
            androidPreferences = "nuvio_season_view_mode",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("season_view_mode")),
        ),
        AccountDataStore(
            name = "PosterCardStyleStorage",
            androidPreferences = "nuvio_poster_card_style",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("poster_card_style_payload")),
        ),
        AccountDataStore(
            name = "CardDepthStyleStorage",
            androidPreferences = "nuvio_card_depth_style",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("card_depth_style_payload")),
        ),
        AccountDataStore(
            // Apple actuals: shared/appleMain TvOsThemeSettingsStore (tvOS) and
            // composeApp/iosMain ThemeSettingsStorage.ios (iOS) — identical key constants.
            name = "ThemeSettingsStorage",
            androidPreferences = "nuvio_theme_settings",
            appleKeys = listOf(
                AppleKeySpec.ProfileScoped("selected_theme"),
                AppleKeySpec.ProfileScoped("amoled_enabled"),
                AppleKeySpec.ProfileScoped("liquid_glass_native_tab_bar_enabled"),
                AppleKeySpec.ProfileScoped("nav_bar_style"),
                // ONLY the legacy per-profile copy. The live key is unscoped
                // ("selected_app_language" with no suffix) and is a device-wide preference that
                // also drives the system "AppleLanguages" key — never wipe that one.
                AppleKeySpec.ProfileScoped("selected_app_language"),
            ),
        ),
        AccountDataStore(
            // iOS-only bridge that publishes the profile chip into the native tab bar. Only the
            // profile-identity keys are listed: the rest ("NuvioNativeTab*") are pure chrome that
            // Compose republishes, and blanking them mid-session buys nothing.
            name = "NativeTabBridge (profile identity)",
            androidPreferences = null,
            appleKeys = listOf(
                AppleKeySpec.Plain("NuvioNativeProfileName"),
                AppleKeySpec.Plain("NuvioNativeProfileAvatarColor"),
                AppleKeySpec.Plain("NuvioNativeProfileAvatarURL"),
                AppleKeySpec.Plain("NuvioNativeProfileAvatarBackgroundColor"),
            ),
        ),

        // ── Notifications ──────────────────────────────────────────────────────────────────────
        AccountDataStore(
            name = "EpisodeReleaseNotificationsStorage",
            androidPreferences = "nuvio_episode_release_notifications",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("episode_release_notifications_payload")),
        ),
        AccountDataStore(
            name = "EpisodeReleaseNotificationPlatform",
            androidPreferences = "nuvio_episode_release_notifications_platform",
            appleKeys = listOf(
                AppleKeySpec.ProfileScoped("episode_release_notification_scheduled_ids"),
            ),
        ),

        // ── Streams ────────────────────────────────────────────────────────────────────────────
        AccountDataStore(
            name = "StreamLinkCacheStorage",
            androidPreferences = "nuvio_stream_link_cache",
            appleKeys = listOf(
                AppleKeySpec.FileStore("StreamLinkCache"),
                // "stream_link_<hash>_<profile>" — hash of the content key.
                AppleKeySpec.DynamicPrefix("stream_link_"),
            ),
        ),
        AccountDataStore(
            name = "BingeGroupCacheStorage",
            androidPreferences = "nuvio_binge_group_cache",
            appleKeys = listOf(
                // "binge_group_<hash>_<profile>" — see BingeGroupCacheRepository.hashedKey.
                AppleKeySpec.DynamicPrefix("binge_group_"),
            ),
        ),
        AccountDataStore(
            name = "StreamBadgeSettingsStorage",
            androidPreferences = "nuvio_stream_badge_settings",
            appleKeys = listOf(
                AppleKeySpec.ProfileScoped("stream_badge_rules"),
                AppleKeySpec.ProfileScoped("show_file_size_badges"),
                AppleKeySpec.ProfileScoped("show_addon_logo"),
                AppleKeySpec.ProfileScoped("stream_badge_placement"),
                // Legacy key this store still reads for migration.
                AppleKeySpec.ProfileScoped("debrid_stream_badge_rules"),
            ),
        ),

        // ── Player ─────────────────────────────────────────────────────────────────────────────
        AccountDataStore(
            name = "PlayerSettingsStorage",
            androidPreferences = "nuvio_player_settings",
            appleKeys = listOf(
                AppleKeySpec.ProfileScoped("show_loading_overlay"),
                AppleKeySpec.ProfileScoped("show_parental_guide"),
                AppleKeySpec.ProfileScoped("resize_mode"),
                AppleKeySpec.ProfileScoped("hold_to_speed_enabled"),
                AppleKeySpec.ProfileScoped("hold_to_speed_value"),
                AppleKeySpec.ProfileScoped("touch_gestures_enabled"),
                AppleKeySpec.ProfileScoped("external_player_enabled"),
                AppleKeySpec.ProfileScoped("external_player_forward_subtitles"),
                AppleKeySpec.ProfileScoped("external_player_send_skip_segments"),
                AppleKeySpec.ProfileScoped("external_player_id"),
                AppleKeySpec.ProfileScoped("preferred_audio_language"),
                AppleKeySpec.ProfileScoped("secondary_preferred_audio_language"),
                AppleKeySpec.ProfileScoped("preferred_subtitle_language"),
                AppleKeySpec.ProfileScoped("secondary_preferred_subtitle_language"),
                AppleKeySpec.ProfileScoped("subtitle_text_color"),
                AppleKeySpec.ProfileScoped("subtitle_background_color"),
                AppleKeySpec.ProfileScoped("subtitle_outline_color"),
                AppleKeySpec.ProfileScoped("subtitle_outline_enabled"),
                AppleKeySpec.ProfileScoped("subtitle_outline_width"),
                AppleKeySpec.ProfileScoped("subtitle_bold"),
                AppleKeySpec.ProfileScoped("subtitle_font_size_sp"),
                AppleKeySpec.ProfileScoped("subtitle_bottom_offset"),
                AppleKeySpec.ProfileScoped("subtitle_use_forced_subtitles"),
                AppleKeySpec.ProfileScoped("subtitle_show_only_preferred_languages"),
                AppleKeySpec.ProfileScoped("addon_subtitle_startup_mode"),
                AppleKeySpec.ProfileScoped("stream_reuse_last_link_enabled"),
                AppleKeySpec.ProfileScoped("stream_reuse_last_link_cache_hours"),
                AppleKeySpec.ProfileScoped("android_playback_engine"),
                AppleKeySpec.ProfileScoped("android_libmpv_video_output"),
                AppleKeySpec.ProfileScoped("android_libmpv_hardware_decoding_enabled"),
                AppleKeySpec.ProfileScoped("android_libmpv_yuv420p_enabled"),
                AppleKeySpec.ProfileScoped("decoder_priority"),
                AppleKeySpec.ProfileScoped("map_dv7_to_hevc"),
                AppleKeySpec.ProfileScoped("tunneling_enabled"),
                AppleKeySpec.ProfileScoped("stream_auto_play_mode"),
                AppleKeySpec.ProfileScoped("stream_auto_play_source"),
                AppleKeySpec.ProfileScoped("stream_auto_play_selected_addons"),
                AppleKeySpec.ProfileScoped("stream_auto_play_selected_plugins"),
                AppleKeySpec.ProfileScoped("stream_auto_play_regex"),
                AppleKeySpec.ProfileScoped("stream_auto_play_timeout_seconds"),
                AppleKeySpec.ProfileScoped("skip_intro_enabled"),
                AppleKeySpec.ProfileScoped("animeskip_enabled"),
                AppleKeySpec.ProfileScoped("animeskip_client_id"),
                AppleKeySpec.ProfileScoped("introdb_api_key"),
                AppleKeySpec.ProfileScoped("intro_submit_enabled"),
                AppleKeySpec.ProfileScoped("stream_auto_play_next_episode_enabled"),
                AppleKeySpec.ProfileScoped("stream_auto_play_prefer_binge_group"),
                AppleKeySpec.ProfileScoped("stream_auto_play_reuse_binge_group"),
                AppleKeySpec.ProfileScoped("next_episode_threshold_mode"),
                AppleKeySpec.ProfileScoped("next_episode_threshold_percent_v2"),
                AppleKeySpec.ProfileScoped("next_episode_threshold_minutes_before_end_v2"),
                AppleKeySpec.ProfileScoped("use_libass"),
                AppleKeySpec.ProfileScoped("libass_render_type"),
                AppleKeySpec.ProfileScoped("ios_video_output_preset"),
                AppleKeySpec.ProfileScoped("ios_tone_mapping_mode"),
                AppleKeySpec.ProfileScoped("ios_target_primaries"),
                AppleKeySpec.ProfileScoped("ios_target_transfer"),
                AppleKeySpec.ProfileScoped("ios_hardware_decoder_mode"),
                AppleKeySpec.ProfileScoped("ios_audio_output_mode"),
                AppleKeySpec.ProfileScoped("ios_extended_dynamic_range_enabled"),
                AppleKeySpec.ProfileScoped("ios_target_colorspace_hint_enabled"),
                AppleKeySpec.ProfileScoped("ios_hdr_compute_peak_enabled"),
                AppleKeySpec.ProfileScoped("ios_deband_enabled"),
                AppleKeySpec.ProfileScoped("ios_interpolation_enabled"),
                AppleKeySpec.ProfileScoped("ios_brightness"),
                AppleKeySpec.ProfileScoped("ios_contrast"),
                AppleKeySpec.ProfileScoped("ios_saturation"),
                AppleKeySpec.ProfileScoped("ios_gamma"),
            ),
        ),
        AccountDataStore(
            // Keys are ProfileScopedKey.of("<field>|<contentId>") → "<field>|<contentId>_<profile>",
            // so the content id sits INSIDE the key and only the "<field>|" prefix is literal.
            // The trailing '|' is what makes each prefix unambiguous (e.g. "subtitle_language|"
            // must not be confused with PlayerSettings' "preferred_subtitle_language").
            name = "PlayerTrackPreferenceStorage",
            androidPreferences = "nuvio_player_track_preferences",
            appleKeys = listOf(
                AppleKeySpec.DynamicPrefix("subtitle_type|"),
                AppleKeySpec.DynamicPrefix("subtitle_language|"),
                AppleKeySpec.DynamicPrefix("subtitle_name|"),
                AppleKeySpec.DynamicPrefix("subtitle_track_id|"),
                AppleKeySpec.DynamicPrefix("addon_subtitle_id|"),
                AppleKeySpec.DynamicPrefix("addon_subtitle_url|"),
                AppleKeySpec.DynamicPrefix("addon_subtitle_addon_name|"),
                AppleKeySpec.DynamicPrefix("audio_language|"),
                AppleKeySpec.DynamicPrefix("audio_name|"),
                AppleKeySpec.DynamicPrefix("audio_track_id|"),
                AppleKeySpec.DynamicPrefix("subtitle_delay_ms|"),
            ),
        ),

        // ── Credentials & third-party services ─────────────────────────────────────────────────
        AccountDataStore(
            name = "DebridSettingsStorage",
            androidPreferences = "nuvio_debrid_settings",
            appleKeys = listOf(
                AppleKeySpec.ProfileScoped("debrid_enabled"),
                AppleKeySpec.ProfileScoped("debrid_cloud_library_enabled"),
                AppleKeySpec.ProfileScoped("debrid_preferred_resolver_provider_id"),
                // Credentials — the leak fixed by adding these to both Apple cleaners.
                AppleKeySpec.ProfileScoped("debrid_torbox_api_key"),
                AppleKeySpec.ProfileScoped("debrid_real_debrid_api_key"),
                AppleKeySpec.ProfileScoped("debrid_alldebrid_api_key"),
                // Premiumize is a registered provider but has no dedicated constant: its key falls
                // through providerApiKeyKey's `else` branch to "debrid_<id>_api_key".
                AppleKeySpec.ProfileScoped("debrid_premiumize_api_key"),
                AppleKeySpec.ProfileScoped("debrid_instant_playback_preparation_limit"),
                AppleKeySpec.ProfileScoped("debrid_stream_max_results"),
                AppleKeySpec.ProfileScoped("debrid_stream_sort_mode"),
                AppleKeySpec.ProfileScoped("debrid_stream_minimum_quality"),
                AppleKeySpec.ProfileScoped("debrid_stream_dolby_vision_filter"),
                AppleKeySpec.ProfileScoped("debrid_stream_hdr_filter"),
                AppleKeySpec.ProfileScoped("debrid_stream_codec_filter"),
                AppleKeySpec.ProfileScoped("debrid_stream_preferences"),
                AppleKeySpec.ProfileScoped("debrid_stream_name_template"),
                AppleKeySpec.ProfileScoped("debrid_stream_description_template"),
                // "debrid_pending_device_authorization_<providerId>_<profile>".
                AppleKeySpec.DynamicPrefix("debrid_pending_device_authorization_"),
                // Catch-all for "debrid_<providerId>_api_key" of any provider id not registered in
                // DebridProviders (loadProviderApiKey/saveProviderApiKey take an arbitrary id and
                // normalize it into the key). Every "debrid_" defaults key in this app is
                // profile-scoped debrid account data, so the broad scan is safe and is what keeps a
                // future provider's API key from surviving sign-out.
                AppleKeySpec.DynamicPrefix("debrid_"),
            ),
        ),
        AccountDataStore(
            name = "TmdbSettingsStorage",
            androidPreferences = "nuvio_tmdb_settings",
            appleKeys = listOf(
                AppleKeySpec.ProfileScoped("tmdb_enabled"),
                // Credential.
                AppleKeySpec.ProfileScoped("tmdb_api_key"),
                AppleKeySpec.ProfileScoped("tmdb_language"),
                AppleKeySpec.ProfileScoped("tmdb_use_trailers"),
                AppleKeySpec.ProfileScoped("tmdb_use_artwork"),
                AppleKeySpec.ProfileScoped("tmdb_use_basic_info"),
                AppleKeySpec.ProfileScoped("tmdb_use_details"),
                AppleKeySpec.ProfileScoped("tmdb_use_release_dates"),
                AppleKeySpec.ProfileScoped("tmdb_use_credits"),
                AppleKeySpec.ProfileScoped("tmdb_use_productions"),
                AppleKeySpec.ProfileScoped("tmdb_use_networks"),
                AppleKeySpec.ProfileScoped("tmdb_use_episodes"),
                AppleKeySpec.ProfileScoped("tmdb_use_season_posters"),
                AppleKeySpec.ProfileScoped("tmdb_use_more_like_this"),
                AppleKeySpec.ProfileScoped("tmdb_use_collections"),
            ),
        ),
        AccountDataStore(
            name = "MdbListSettingsStorage",
            androidPreferences = "nuvio_mdblist_settings",
            appleKeys = listOf(
                AppleKeySpec.ProfileScoped("mdblist_enabled"),
                // Credential.
                AppleKeySpec.ProfileScoped("mdblist_api_key"),
                AppleKeySpec.ProfileScoped("mdblist_use_imdb"),
                AppleKeySpec.ProfileScoped("mdblist_use_tmdb"),
                AppleKeySpec.ProfileScoped("mdblist_use_tomatoes"),
                AppleKeySpec.ProfileScoped("mdblist_use_metacritic"),
                AppleKeySpec.ProfileScoped("mdblist_use_trakt"),
                AppleKeySpec.ProfileScoped("mdblist_use_letterboxd"),
                AppleKeySpec.ProfileScoped("mdblist_use_audience"),
                AppleKeySpec.ProfileScoped("mdblist_use_mal"),
            ),
        ),
        AccountDataStore(
            name = "TraktAuthStorage",
            androidPreferences = "nuvio_trakt_auth",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("trakt_auth_payload")),
        ),
        AccountDataStore(
            name = "TraktSettingsStorage",
            androidPreferences = "nuvio_trakt_settings",
            appleKeys = listOf(
                AppleKeySpec.ProfileScoped("trakt_settings_payload"),
                AppleKeySpec.ProfileScoped("pending_watch_progress_source"),
            ),
        ),
        AccountDataStore(
            name = "TraktCommentsStorage",
            androidPreferences = "nuvio_trakt_comments",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("comments_enabled")),
        ),
        AccountDataStore(
            name = "TraktLibraryStorage",
            androidPreferences = "nuvio_trakt_library",
            appleKeys = listOf(
                AppleKeySpec.FileStore("TraktLibrary"),
                AppleKeySpec.ProfileScoped("trakt_library_payload"),
            ),
        ),
        AccountDataStore(
            name = "SimklAuthStorage",
            androidPreferences = "nuvio_simkl_auth",
            appleKeys = listOf(AppleKeySpec.ProfileScoped("simkl_auth_payload")),
        ),
        AccountDataStore(
            name = "SimklSyncStorage",
            androidPreferences = "nuvio_simkl_sync",
            appleKeys = listOf(
                AppleKeySpec.FileStore("SimklSync"),
                AppleKeySpec.ProfileScoped("simkl_sync_snapshot"),
            ),
        ),
        AccountDataStore(
            // composeApp-only (phone flavours); tvOS does not ship P2P, but both Apple cleaners
            // already list these keys, so they stay here.
            name = "P2pSettingsStorage",
            androidPreferences = "torrent_settings",
            appleKeys = listOf(
                AppleKeySpec.ProfileScoped("p2p_enabled"),
                AppleKeySpec.ProfileScoped("enable_upload"),
                AppleKeySpec.ProfileScoped("hide_torrent_stats"),
            ),
        ),
    )

    /** SharedPreferences file names for the Android cleaner's whole-file `clear()`. */
    fun androidPreferenceNames(): List<String> =
        all.mapNotNull { it.androidPreferences }.distinct()

    /** Unscoped keys — remove verbatim. */
    fun applePlainKeys(): List<String> =
        appleKeys().filterIsInstance<AppleKeySpec.Plain>().map { it.key }.distinct()

    /** Base keys — remove `"<base>_<profileId>"` for every profile slot (1..MAX_PROFILES). */
    fun appleProfileScopedBases(): List<String> =
        appleKeys().filterIsInstance<AppleKeySpec.ProfileScoped>().map { it.base }.distinct()

    /** Prefixes — remove `"<prefix><profileId>"` for every profile slot (1..MAX_PROFILES). */
    fun appleProfileIndexedPrefixes(): List<String> =
        appleKeys().filterIsInstance<AppleKeySpec.ProfileIndexed>().map { it.prefix }.distinct()

    /** Prefixes to match while scanning `NSUserDefaults.dictionaryRepresentation()`. */
    fun appleDynamicPrefixes(): List<String> =
        appleKeys().filterIsInstance<AppleKeySpec.DynamicPrefix>().map { it.prefix }.distinct()

    /** `PayloadFileStore` subdirectories to delete wholesale. */
    fun appleFileStoreSubdirectories(): List<String> =
        appleKeys().filterIsInstance<AppleKeySpec.FileStore>().map { it.subdirectory }.distinct()

    private fun appleKeys(): List<AppleKeySpec> = all.flatMap { store -> store.appleKeys }
}
